packages:
  - docs
  - packages/*

catalogs:
  default:
    "@astrojs/solid-js": 6.0.1
    "@astrojs/starlight": 0.38.2
    astro: 6.1.3
    jsdom: 29.0.1
    sharp: 0.34.5
    solid-js: 1.9.12
    typescript: 6.0.2
    vite: npm:@voidzero-dev/vite-plus-core@latest
    vite-plus: latest
    vitest: npm:@voidzero-dev/vite-plus-test@latest

onlyBuiltDependencies:
  - esbuild
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
